import { FieldControl } from '$/client/components/form/controls/field-control';
import { LabelControl } from '$/client/components/form/controls/label-control';
import { Select } from '$/client/components/form/select';
import { Textarea } from '$/client/components/form/textarea';
import { TextField } from '$/client/components/form/textfield';
import { Button } from '$/client/components/ui/button';
import {
	updatePersonalInfoSchema,
	type UpdatePersonalInfoInput,
} from '$/shared/schemas/user/update-personal-info.schema';
import { MAX_BIO_LENGTH } from '$/shared/schemas/user/user.schema';
import { socialLinkTypes, type UserDetails } from '$/shared/types/users';
import { zodResolver } from '@hookform/resolvers/zod';
import { useMemo } from 'react';
import { FormProvider, useFieldArray, useForm, useFormContext } from 'react-hook-form';

type Props = {
	user: UserDetails;
	onSubmit: (input: UpdatePersonalInfoInput) => void;
	loading?: boolean;
};

// TODO:
// 1. change the button to disabled when there are no changes
// 2. add profile picture upload functionality
// 3. send to the server only the fields that were updated/touched
export function PersonalInfoForm({ user, onSubmit, loading }: Props) {
	const formMethods = useForm<UpdatePersonalInfoInput>({
		defaultValues: {
			...user,
			socialLinks: user.socialLinks ?? [],
		},
		resolver: zodResolver(updatePersonalInfoSchema),
	});

	const {
		register,
		handleSubmit,
		formState: { errors },
		watch,
	} = formMethods;

	return (
		<FormProvider {...formMethods}>
			<form className='flex flex-col gap-4' onSubmit={handleSubmit(onSubmit)}>
				<div>profile picture</div>
				<div className='flex gap-8'>
					<TextField
						label='First Name'
						error={errors.firstName?.message}
						{...register('firstName')}
					/>
					<TextField
						label='Last Name'
						error={errors.lastName?.message}
						{...register('lastName')}
					/>
				</div>

				<TextField label='Email' error={errors.email?.message} {...register('email')} />
				<Textarea
					label='Bio'
					limit={MAX_BIO_LENGTH}
					error={errors.bio?.message}
					value={watch('bio') || ''}
					{...register('bio')}
				/>

				<SocialLinksSection />

				<Button type='submit' className='self-end rounded-sm' loading={loading}>
					Save Changes
				</Button>
			</form>
		</FormProvider>
	);
}

function SocialLinksSection() {
	const {
		control,
		register,
		formState: { errors },
	} = useFormContext<UpdatePersonalInfoInput>();
	const { fields, append, remove } = useFieldArray({
		control,
		name: 'socialLinks',
		keyName: 'autoGeneratedId',
	});

	const selectSocialLinkTypeItems = useMemo(
		() =>
			socialLinkTypes.map((type) => ({
				label: type,
				value: type,
			})),
		[],
	);

	return (
		<div className='flex flex-col gap-2'>
			<span className='text-xl font-medium'>Social Links</span>
			<div className='flex flex-col'>
				{fields.map((field, index) => {
					const typeRegister = register(`socialLinks.${index}.type`);

					return (
						<div
							key={field.id || field.autoGeneratedId}
							className='flex items-center gap-6'
						>
							<div className='flex w-full gap-6'>
								<FieldControl className='w-auto'>
									<LabelControl name={typeRegister.name} label='Type'>
										<Select
											items={selectSocialLinkTypeItems}
											{...typeRegister}
											onSelect={(value) => {
												typeRegister.onChange({ target: { value } });
											}}
										/>
									</LabelControl>
								</FieldControl>
								<TextField
									label='URL'
									{...register(`socialLinks.${index}.url`)}
									error={errors.socialLinks?.[index]?.url?.message}
									placeholder='https://www.example.com'
								/>
							</div>
							<Button
								type='button'
								className='text-eerie-black mt-5 flex h-5 w-5 justify-center bg-gray-200 p-0 text-sm hover:bg-gray-300'
								onClick={() => remove(index)}
							>
								X
							</Button>
						</div>
					);
				})}
				<Button
					type='button'
					className='text-celestial-blue hover:text-celestial-blue-hover m-0 mt-2 self-start bg-transparent p-0 font-medium hover:bg-transparent'
					onClick={() => append({ url: '', type: 'Other' })}
				>
					+ Add social link
				</Button>
			</div>
		</div>
	);
}
